### ISSUE TITLE
Yêu cầu hỗ trợ thay đổi cách ghi nhận dữ liệu bệnh nhân nhận thuốc lao theo hẹn khi đăng ký KCB và điều kiện lấy mã đối tượng KCB 7.1 (Lĩnh thuốc không khám bệnh)

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/THEO-DOI-THUC-HIEN#105]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_mong_muon_hoan_thanh](https://img.shields.io/badge/Ngày%20mong%20muốn%20hoàn%20thành-:-blue?style=plastic&logo=github) **nguoi_ghi_nhan_ghi**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **to_truong_ghi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **tất cả**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_quangngai_maloaikcb_lao_79_4750_07082024`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/9JnMfHjH4)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Register, Prescription , Admin`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

- Nhận bệnh: Yêu cầu khi check bệnh nhân khám lao (lĩnh thuốc lao) thì cho mặc định ghi nhận trạng thái chuyển tuyến bằng 5 (Giấy hẹn lĩnh thuốc) hoặc thêm chức năng chọn trạng thái chuyển tuyến vào tab Khám lao . Do hiện tại phần mềm bắt buộc nhập giấy chuyển tuyến thì mới được chọn trạng thái chuyển tuyến mà bệnh nhân lĩnh thuốc lao không có giấy chuyển không chọn được trạng thái làm sai dữ liệu XML mã loại KCB. (XML1 MA_LOAI_KCB bệnh nhân lãnh thuốc không khám = 07)

![ảnh](https://github.com/user-attachments/assets/a22c0d4e-a1b6-4ea9-9474-bd90cbabff4e)
![ảnh](https://github.com/user-attachments/assets/0530cad7-bfe0-425f-8d9b-efb5cc8771c0)
![ảnh](https://github.com/user-attachments/assets/da401482-4d54-4101-a98c-d8833a436366)

- Admin thay đổi điều kiện để xuất XML1 cột MA_DOITUONG_KCB = 7.1 (Người bệnh đến cơ sở khám bệnh, chữa bệnh lĩnh thuốc). psdangky.manoigt <> '' hoặc psdangky.mabv_dieutri_lao <> '' vì người bệnh đến cơ sở KCB lĩnh thuốc thì không cần giấy chuyển và chỉ có giấy xác nhận lao . (Cần xem lại điều kiện này có thật sự cần thiết không)

![ảnh](https://github.com/user-attachments/assets/e74e098b-e30c-4b6f-bed1-18ab1b70cdd4)
![ảnh](https://github.com/user-attachments/assets/4a562fb7-0b8e-4039-8af6-43a1b861491d)

___
### ☑ TỔ LẬP TRÌNH - CHI TIẾT CÔNG VIỆC ☑
[Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
___

- [x] #108

- [x] #109

___

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-14**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: 

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận
⌛ Thời gian hoàn thành dự kiến: 2024-08-14

**Comment by vinh-dh** [comment]
Cập nhật [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
- Bổ sung điều kiện ràng buộc cột `psdangky.trangthaichuyentuyen` đối với người bệnh khám lao khi tiếp nhận bệnh.
![image](https://github.com/user-attachments/assets/afd147cb-1169-440d-bb03-9cf89dc6c11b)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-19**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @chauthanhtra @le-an-87 @nghivanbi

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '26/08/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Register 19/08

- Nội dung: Form nhận bệnh đã hỗ trợ khi check bệnh nhân khám lao thì phần mềm tự lấy trượng thái chuyển tuyến bằng 5 (Giấy hẹn lãnh thuốc)

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/f5e8bc22-30bd-4d3a-be02-39685eb2ff8f)
![ảnh](https://github.com/user-attachments/assets/e8dd91bd-f2b5-4b8f-a4d2-db45fd415b57)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi: Hiệu chỉnh thông tin chưa hỗ trợ tự lấy trạng thái chuyển tuyến = 5 (Giấy hẹn lãnh thuốc) khi check bệnh nhân khám Lao


- Hình ảnh lỗi:

![ảnh](https://github.com/user-attachments/assets/ecea853f-2d2c-45cd-8a39-24baf1521fb1)
![ảnh](https://github.com/user-attachments/assets/f4ce4da1-660d-4f20-8088-8c7400f84ff0)


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm Admin 19/08 
***

>- Nội dung: 



>- Hình ảnh: 



***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi: MA_DOITUONG_KCB chưa lấy theo mô tả mới trường hợp MA_DOITUONG_KCB  = 7.1

  - Khám ngoại trú. Thỏa cả 2 điều kiện:
  - psdangky.tuyen = 0 và
  - psdangky.manoigt <> '' hoặc psdangky.mabv_dieutri_lao <> '' và
  - psdangky.trangthaichuyentuyen = 5

Thỏa điều kiện nhưng phần mềm đang xuất MA_DOITUONG_KCB = 3.3

- Hình ảnh lỗi:

![ảnh](https://github.com/user-attachments/assets/b3ad289d-9d7a-4b62-98c5-568eebc96272)
![ảnh](https://github.com/user-attachments/assets/4e130338-1ea9-4ae9-9d41-2e4fb3baf72b)
![ảnh](https://github.com/user-attachments/assets/46d719cd-2eb2-492d-a329-50fa0ed1efbe)


> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @lequocthong29 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**:  ![](https://i.imgur.com/BAV5IKF.png)

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @ongtrieuhau
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
- ⌛ Thời gian hoàn thành dự kiến: **2024-**
-  📣 **Lưu ý khi tiếp nhận**: ![](https://i.imgur.com/y40s4LS.png)

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalRegister.exe v.3.24.0821.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32408210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32408210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalRegisterexe%2F32408210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: Fix - Hiệu chỉnh thông tin chưa hỗ trợ tự lấy trạng thái chuyển tuyến = 5(Giấy hẹn lãnh thuốc) khi check bệnh nhân khám lao

- 🐛: Fix - Thiếu thông tin Check giấy xác nhận lưu trú và chọn giấy lưu ở tab Thông tin thêm

- ☑: https://github.com/dh-hos/dhg.hospitaladmin/issues/89

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/105

![](https://i.imgur.com/HU06FFQ.png)

![](https://i.imgur.com/aVn0Vhd.png)

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40lequocthong29-informational?logo=github)](https://github.com/lequocthong29) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalRegister.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: ' 23/8/2024  '.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0821.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408210-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408210-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408210-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **Chỉnh lỗi**: **_Yêu cầu hỗ trợ thay đổi cách ghi nhận dữ liệu bệnh nhân nhận thuốc lao theo hẹn khi đăng ký KCB và điều kiện lấy mã đối tượng KCB 7.1 (Lĩnh thuốc không khám bệnh)_**

- 🐛: XML01.MA_DOITUONG_KCB lấy sai điều kiện 7.1 ![](https://i.imgur.com/hHMPD3g.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/105

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.0821.0
***
>Kết quả đã hoàn thành 
- Nội dung: Admin đã Cập nhật mà đối tượng KCB = 7.1 như mô tả


- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/1bedeb6b-d90e-4059-94f8-3dcb6073225d)
![ảnh](https://github.com/user-attachments/assets/674fc940-a551-4773-8aab-cee341b265bf)
![ảnh](https://github.com/user-attachments/assets/90c89137-6a58-4d42-9957-530fdcdbf15f)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm 
***
>Kết quả đã hoàn thành 
- Nội dung: 

Hiệu chỉnh thông tin đã hỗ trợ lấy trạng thái chuyển tuyến bằng 5 (Giấy hẹn lãnh thuốc) khi check bệnh nhân khám lao
Test bệnh nhân mới cấp toa, in bảng kê, xuất XML bình thường chưa phát hiện lỗi mới

- Hình ảnh: 

![ảnh](https://github.com/user-attachments/assets/7149e878-f742-4cb9-bc1e-86066fd916e3)
![ảnh](https://github.com/user-attachments/assets/6b737eb7-7722-482c-8cf5-5d3808d459f7)
![ảnh](https://github.com/user-attachments/assets/64e871ca-a061-4d12-8b6f-c24330c96d19)
![ảnh](https://github.com/user-attachments/assets/b826c602-4096-42c9-a0b4-c286fa4ac75e)


***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
