### ISSUE TITLE
LỖI KHI GỬI XML4750 LÊN CỔNG VÀ XUẤT XML4750

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN#110]

**Comment by minhduc2it** [comment]
Data: duc_ub_loixml
Port postgres: 5434
Link tải data: https://gofile.me/78TQg/zZOGdmxAo

MaBN: 2022036233 - MaKB: 2408001570 - MaBA: 015839 - NgayKCB: 07/08/2024 - MaDV: 05 - ThangKT: 08 - NamKT: 2024

LỖI KHI GỬI XML4750 LÊN CỔNG VÀ XUẤT XML4750

![image](https://github.com/user-attachments/assets/731049c2-e50f-4cd2-9e7f-d578d9201332)

![image](https://github.com/user-attachments/assets/da59c675-d27d-4b20-868c-6b3bef9b6758)

**Chi tiết lỗi:**
Error [0]Message: Lỗi code [OTH.Adapter.HosBHXH.AGiamDinh.loadData].
Error [0]HResult: -2146233088
Error [0]Source: OTH.Adapter
Error [0]StackTrace:    at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
   at OTH.XForms.HosAdmin.Reports.XFrmBKXuatXML4750.PopMenu_ItemClick(Object sender, ItemClickEventArgs e)
Error [0]TargetSite: Void loadData()

Error [1]=== INNER EXCEPTION ===
Error [1]Message: The source contains no DataRows.
Error [1]HResult: -2146233079
Error [1]Source: System.Data.DataSetExtensions
Error [1]StackTrace:    at System.Data.DataTableExtensions.LoadTableFromEnumerable[T](IEnumerable`1 source, DataTable table, Nullable`1 options, FillErrorEventHandler errorHandler)
   at System.Data.DataTableExtensions.CopyToDataTable[T](IEnumerable`1 source)
   at OTH.Adapter.HosBHXH.AGiamDinh.loadData()
Error [1]TargetSite: System.Data.DataTable LoadTableFromEnumerable[T](System.Collections.Generic.IEnumerable`1[T], System.Data.DataTable, System.Nullable`1[System.Data.LoadOption], System.Data.FillErrorEventHandler)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-19**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0816.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408161-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408161-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408161-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **Chỉnh lỗi**: **_LỖI KHI GỬI XML4750 LÊN CỔNG VÀ XUẤT XML4750_** ![](https://i.imgur.com/EnsOczn.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/110

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã Kiểm tra Xem XML4750 thành công
![image](https://github.com/user-attachments/assets/2741df6d-fc79-413a-893b-70f54f08e64c)
