### ISSUE TITLE
XML9 MA_THE_TAM KHÔNG LOAD DỮ LIỆU

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN#113]

**Comment by minhduc2it** [comment]
Data: duc_dangtt_xml9mathetam
Port Postgres: 5434
Link tải data: https://gofile.me/78TQg/NLNEXNukP
---
MaBN: 2024013669 - MaKB: 2408003472 - MaBA: 2024007246 - Ngay ra viện: 20/08/2024 - MaDV: 17 - ThangKT: 08 - NamKT: 2024


Theo [Mô tả XML9](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang09%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md): ttcon.thetam = 1 thì: ma_the_tam = ttcon.mathe

Thông tin con có check Thẻ tạm
![image](https://github.com/user-attachments/assets/e9ebbbc1-3522-4a57-a004-233cf65d2a8b)

XML4750 XML9 cột MA_THE_TAM không load Mã thẻ tạm của con
![image](https://github.com/user-attachments/assets/e6098d7c-62d1-4412-9cc0-5bd8d93f4aa3)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-08-26**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @minhduc2it @le-an-87 
- Đã kiểm tra bằng phiên bản mới nhất không còn lỗi này ![](https://i.imgur.com/kv7wBlD.png)

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã Kiểm tra XML9 cột Ma_the_tam đã load Mã thẻ
![image](https://github.com/user-attachments/assets/ba85b885-28af-4ce8-a0a3-a715fc3e504a)
