### ISSUE TITLE
Module admin không hoạt động được khi thực hiện gửi xml 4750

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN#116]
Admin cài đặt tại cơ sở khách hàng.
Chức năng gửi xml 4750 khi thực hiện gửi xml.
-> phần mềm thực hiện gửi và tự đóng / ẩn thông báo.
=> không sử dụng tiếp được nữa.
Data: an_sadec_xml4750_admin_27082024
port: 5434
link: https://gofile.me/78TQg/aztTR6qJR
Thực hiện gửi xong phần mềm hiển thị như hình không thao tác được nữa
![ảnh](https://github.com/user-attachments/assets/ed2ed56d-7ca7-4e3c-bec8-db65e3110d76)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-02**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0829.3 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408293-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408293-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32408293-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Module admin không hoạt động được khi thực hiện gửi xml 4750_**

- 🐛: Bỏ thông báo lỗi khi gửi nhiều hồ sơ

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/116

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '05/09/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
Đã nhờ khách hàng test thử.
> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/06e2aa6a-fe7c-494f-adae-d31c4ba97b76)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
