### ISSUE TITLE
XML3 ngày giờ thực hiện y lệnh lớn hơn ngày giờ trả kết quả xét nghiêm (BV Đông Hải)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN#117]
XML3 Cận lâm sàng xét nghiệm có ngày giờ thực hiện y lệnh lớn hơn ngày trả kết quả.
data: an_donghai_ngayylenhxn_30082024
https://gofile.me/78TQg/5TbfZkIaw
port: 5434

mabn | makb | maba | madv | maphong | ngaykcb | macls | thangkt | namkt | ngaycd | giolaymau | ngaykq
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
2018006103 | 2407000008 | 2024002409 | 02 |   | 01/07/2024 2:55 | DI32 | 07 | 2024 | 01/07/2024 2:55 | 01/07/2024 6:27 | 01/07/2024 3:30

![ảnh](https://github.com/user-attachments/assets/8705ca4d-b25b-484e-8215-31920b91a293)
![ảnh](https://github.com/user-attachments/assets/0f655c4c-d7d3-4f45-bf07-90821624d568)
***
- BV Đông Hải báo phần mềm ghi nhận sai thời gian lấy mẫu.
-> Hiện tại phần mềm cho phép chỉnh ngày kết quả xét nghiệm nhỏ hơn thời gian lấy mẫu và không có nhật ký ghi nhận ngày giờ thực hiện lấy mẫu và trả kết quả.
=> dẫn đến không xác định được là lỗi do người dùng hay lỗi do phần mềm.

Đề xuất:
1. Ghi nhận nhật ký lấy mẫu và trả kết quả.
2. Ràng buộc không cho phép chỉnh ngày kết quả trước thời gian lấy mẫu.
3. Bổ sung chức năng cho phép chỉnh thời gian lấy mẫu và hiển thị thời gian lấy mẫu để người dùng dễ kiểm soát.

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
👉 Thực hiện:
- Lỗi ngày kq < ngày lấy mẫu để anh kiểm tra. <= Anh rà soát và có ràng buộc không cho phép ngày kq < ngày lấy mẫu.
- "Ghi nhận nhật ký lấy mẫu và trả kết quả." <= phần này không cần đâu. Ghi nhận thì dữ liệu không chịu nổi đâu, nhật ký chỉ khi nào có điều chỉnh hoặc thay đổi mới ghi.
- "Bổ sung chức năng cho phép chỉnh thời gian lấy mẫu và hiển thị thời gian lấy mẫu để người dùng dễ kiểm soát." <= Anh bổ sung thêm cột thể hiện thời gian lấy mẫu lúc thực hiện, cho phép người dùng điều chỉnh tại đây.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 DH.Laboratory.exe v.3.24.0906.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32409060-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32409060-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FDHLaboratoryexe%2F32409060-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Kiểm tra [thời gian đọc kết quả xét nghiệm] >= [thời gian lấy mẫu].

- ✨: Cho phép điều chỉnh [thời gian lấy mẫu] tại form thực hiện xét nghiệm.

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/117

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Laboratory.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/b3dc385a-95f3-469e-9dde-2f1fdee2bb01)
![ảnh](https://github.com/user-attachments/assets/3b392d6e-eacc-4950-9cc1-7db039d7066f)
![ảnh](https://github.com/user-attachments/assets/909eb0b0-1847-48f4-ab61-3e96bf87162d)


> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu:

- [ ] Đã bổ sung trường ngày giờ lấy mẫu và cho phép điều chỉnh
- [ ] Đã bổ sung ràng buộc không cho phép chỉnh thời gian kết quả nhỏ hơn thời gian lấy mẫu.

***
- Tiến hành hỗ trợ khách hàng.
