### ISSUE TITLE
XML13: TOMTAT_KQ không load dữ liệu

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN#120]

**Comment by minhduc2it** [comment]
Data: duc_tracu_xml13tomtatkq
Port: 5434
Link data: https://gofile.me/78TQg/HKEI3FykM
---
MaBN: 2023014794 - MaKB: 2408011922 - MaBA: 2024012786 - Ngay ra viện: 27/08/2024 - MaDV: CC - ThangKT: 08 - NamKT: 2024
---
Theo [Mô tả XML13](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang13%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md): tomtat_kq = bnnoitru.tomtat_kq

bnnoitru.tomtat_kq có dữ liệu, nhưng XML13 cột tomtat_kq không load dữ liệu

![image](https://github.com/user-attachments/assets/61b39aab-2bb8-494c-87dc-e6452fd82011)

![image](https://github.com/user-attachments/assets/7e70cdf6-6204-4929-8a4c-28ced4a15bef)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-09**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0903.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409030-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409030-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409030-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_XML13: TOMTAT_KQ không load dữ liệu_**

- 🐛:XML13.TOMTAT_KQ không lấy được dữ liệu ![](https://i.imgur.com/tDtuPN9.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/120

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra thành công
![image](https://github.com/user-attachments/assets/ff4d612c-40d4-4056-974e-5ec44d1489ad)
