### ISSUE TITLE
XML4750 lấy sai mã đối tượng trường hợp bệnh án ngoại trú có bổ sung thông tin giấy hẹn (BV Cù Lao Minh)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN#121]
XML4750 lấy sai mã đối tượng trường hợp bệnh án ngoại trú có bổ sung thông tin giấy hẹn (BV Cù Lao Minh)
data: an_culaominh_06092024_1 https://gofile.me/78TQg/ciSzQIuPI
port: 5434

mabn | makb | maba | madv | maphong | ngayrv | thangkt | namkt
-- | -- | -- | -- | -- | -- | -- | --
2018002288 | 2408001833 | N2024000890 | 03 | CC | 30/08/2024 17:01 | 08 | 2024

- Bệnh án ngoại trú đã bổ sung thông tin giấy hẹn những xml4750 vẫn không xuất được mã đối tượng 1.5
(dữ liệu bnnoitru.manoigt = '')

![ảnh](https://github.com/user-attachments/assets/991d15b4-ce8c-45cb-8715-f3d8363c7803)
![ảnh](https://github.com/user-attachments/assets/1ce0da71-79c5-4ed1-922c-f68848aeedac)
![ảnh](https://github.com/user-attachments/assets/ba482901-e848-40c5-b2e7-27d3708b9cb1)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: _Chức năng xuất XML4750 thực hiện đúng theo mô tả_
- 📣: @le-an-87  hướng dẫn khách hàng nhập mã nơi giới thiệu sẽ xuất XML đúng theo mô tả ![](https://i.imgur.com/iUEScQW.png) ![](https://i.imgur.com/Ov4AFsA.png)


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
anh @ongtrieuhau cho em hỏi.
- Bệnh án ngoại trú khi chỉnh thông tin muốn nhập giấy chuyển tuyến là phải nhập ở chức năng nào mới đúng?
- 
***

**Comment by ongtrieuhau-dh** [comment]
### 📢 @le-an-87 

- Hiện là phải đủ 2 điều kiện là có nơi giới thiệu và có trạng thái chuyển tuyến nhé. ![](https://i.imgur.com/H8IUnrZ.png)

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
Em hỏi chổ nào cập nhật thông tin chuyển viện bệnh án ngoại trú?
anh nói phải đủ thông tin nếu phần mềm không cập nhật được phải hướng dẫn bệnh viện vào chỉnh ở dữ liệu hay sao?
***

**Comment by ongtrieuhau-dh** [comment]
Chưa hiểu, ở trên là hỏi thông tin chuyển tuyến mà ![](https://i.imgur.com/2shvUgv.png)

**Comment by ongtrieuhau-dh** [comment]
Hiện tại muốn chỉnh thông tin bệnh nhân ngoại trú thì bệnh nhân ở trạng thái Chưa ra viện nhé. Có thể tham khảo theo git này [Hiệu chỉnh thông tin BANT không tìm thấy thông tin bệnh nhân](https://github.com/dh-hos/dhg.hospitalprescription/issues/325)
