### ISSUE TITLE
XML4750 load hồ sơ có chi phí 0đ (BV Ô Môn)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN#122]
XML 4750 vẫn load các hồ sơ có chi phí thanh toán 0 đồng (Bệnh án ARV)
data: an_omon_xml_06092024  https://gofile.me/78TQg/FkAU4NeBN
port: 5434
mabn | makb | maba | madv | maphong | ngaykcb | thangkt | namkt
-- | -- | -- | -- | -- | -- | -- | --
2017008337 | 2408029085 | N2017000495 | 008 | PL | 30/08/2024 7:16 | 08 | 2024
***
Module: Admin, Reports
Đề xuất không load các hồ sơ có chi phí thanh toán bảo hiểm 0đ.
![ảnh](https://github.com/user-attachments/assets/cb2658f8-aacb-4b4e-af1a-c0784cdb23ea)
![ảnh](https://github.com/user-attachments/assets/9ccfde40-6d56-45a0-b34e-7ac563f0c9dc)

___
### ☑ TỔ LẬP TRÌNH - CHI TIẾT CÔNG VIỆC ☑
___

- [x] #123

- [x] #124

___

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-13**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 Reports.exe v.3.24.0909.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409090-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409090-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FReportsexe%2F32409090-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Bổ sung điều kiện để loại bỏ các hồ sơ không có chi phí.

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/123

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/122

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40vinh--dh-informational?logo=github)](https://github.com/vinh-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/Reports.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87

**Comment by le-an-87** [comment]
### **Đề nghị cung cấp thêm thông tin xử lý**
- Yêu cầu cung cấp thông tin: 'Module admin có chỉnh luôn không anh?'.

**Comment by ongtrieuhau-dh** [comment]
Hiện tại những hồ sơ nào sai, thì sẽ hỗ trợ xóa thôi, phần admin chưa có chỉnh theo cái này nhé, vì có những hồ sơ, module cũ chưa cập nhật tất cả hồ sơ khi ra viện. Cơ bản đối chiếu sẽ là giữa 4210 và 4750 nhé @le-an-87

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi:

- Hình ảnh lỗi:

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/9efec2dc-2e21-4bc0-99bb-febb03ec4b68)
![ảnh](https://github.com/user-attachments/assets/821cd1b0-9e1d-49ee-aa5c-f8b31b6043e7)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
