### ISSUE TITLE
XML4750: tab D.S Xml load sai ma_lk so với ma_lk trên XML01

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN#125]

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-16**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
### 📢 @minhduc2it 
---

- Lỗi này, nhờ @minhduc2it xử lý xóa tay những MA_LK bị sai
- Lỗi này sẽ chỉnh theo git này [Yêu cầu - Hỗ trợ lại cách lấy dữ liệu 4750 bị double nhiều dòng](https://github.com/dh-hos/To_Lap_Trinh/issues/628)

**Comment by ongtrieuhau-dh** [comment]
### 📢 @minhduc2it 

- ![](https://i.imgur.com/7owa1r8.png)

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
Đã kiểm tra thành công
![image](https://github.com/user-attachments/assets/8aed6cea-5642-4230-a4d1-2ce6a7530e2c)
