### ISSUE TITLE
Bệnh nhân nội trú có thanh toán chi phí ngoại trú XML4750 admin không load được hs ngoại trú

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN#126]
Bệnh nhân nhập viện bệnh án nội trú có toa thuốc ngoại trú và thực hiện thanh toán xml ngoại trú và xml nội trú.
Admin chức năng xuất xml 4750 không load được hs ngoại trú.
data: an_thoilai_xml4750_09092024 
port: 5434
link: https://gofile.me/78TQg/Yvwltx709

mabn | makb | maba | ngaydk | madv | maphong | thangkt | namkt
-- | -- | -- | -- | -- | -- | -- | --
2022026842 | 2408008903 | 2024003270 | 23/08/2024 7:39 | 10 | 01 | 08 | 2024

![ảnh](https://github.com/user-attachments/assets/d0d84446-0193-4a42-bb72-06c23da1bc09)

hs ngoại trú
![ảnh](https://github.com/user-attachments/assets/677f4e2f-4fa1-4a94-a635-5d91e87dcd29)
![ảnh](https://github.com/user-attachments/assets/e3d31fc5-0032-4e22-a558-c9df36e67d52)
![ảnh](https://github.com/user-attachments/assets/4650022c-4c26-4cc2-b598-116d0c060863)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-16**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0911.5 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409115-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409115-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409115-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_Bệnh nhân nội trú có thanh toán chi phí ngoại trú XML4750 admin không load được hs ngoại trú_**

- 🐛:Fix lỗi load thiếu hồ sơ ngoại trú (khi có bệnh án nội trú ) ![](https://i.imgur.com/ILGskmX.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/126

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***

> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/6be3bd47-e8a6-4861-bf5b-ec2cb3c3f10e)

![ảnh](https://github.com/user-attachments/assets/149cb9e2-ace5-4190-8f9f-9d166ad7496b)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
