### ISSUE TITLE
XML 4750 Bệnh nhân lao (BANT ngày) lấy sai mã đối tượng (BV Quảng ngãi)

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/THEO-DOI-THUC-HIEN#127]
Data: an_quanngai_khamlao_12092024 link: https://gofile.me/78TQg/RgAVW076a
port: 5432

mabn | makb | maba | madv | maphong | thangkt | namkt | mabv_dieutri_lao | trangthaichuyentuyen
-- | -- | -- | -- | -- | -- | -- | -- | --
2024017062 | 2408009062 | N2024001471 | 10 | B-LAO | 08 | 2024 | 51014 | 5

Bệnh án ngoại trú thanh toán ngày có check BN Lao và trạng thái chuyển tuyến = 5
-> XML 4750 lấy sai mã đối tượng
![ảnh](https://github.com/user-attachments/assets/a2ec0263-651a-4270-8a3f-1ccc11585855)
![ảnh](https://github.com/user-attachments/assets/5a5ec0e9-daaa-45d7-9ac3-d3cf4cf89c8c)
![ảnh](https://github.com/user-attachments/assets/da1310a9-11f5-40c2-9f33-8f3a7908e882)
___
### ☑ TỔ LẬP TRÌNH - CHI TIẾT CÔNG VIỆC ☑
___

- [ ] #129

- [x] #130

___

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-17**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
## HD.09 [^HD09]
-  ✔️ **Phê duyệt YC theo HD.08** 
-  👉 **Assign**: @vinh-dh 
-  👉 **Thực hiện các yêu cầu theo luồng công việc này**
-  📣 **Lưu ý khi tiếp nhận**: Xem mô tả thêm trường hợp này ![](https://i.imgur.com/VtMbhxu.png)

1. _Ghi nhận thời gian hoàn thành dự kiến, theo định dạng yyyy-MM-dd, và thời gian hoàn thành không được lớn hơn thời gian dự kiến ở HD.05_ 
2. _Trường hợp không tiếp nhận hoặc thời gian không đúng với thời gian dự kiến ở HD.05 phải nêu rõ lý do._
3. _Theo dõi vi phạm HD.04 của luồng công việc này theo_ **HD.04** [^HD04]
4. _Cập  nhật sản phẩm để giải quyết luồng công việc này, diễn giải đầy đủ chức năng mới, chỉnh sửa lỗi theo mẫu READMECODING.md khi push code, có kèm hình ảnh hoặc tài liệu xác định đã có các chức năng mới, chỉnh lỗi xong._


[^HD09]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút), Trách nhiệm: theo dõi đến khi Close Issue
[^HD04]: Nghĩa vụ: ghi nhận đầy đủ thông tin

**Comment by vinh-dh** [comment]
✔️ Đã tiếp nhận.
⌛ Thời gian hoàn thành dự kiến: 2024-09-13

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
sao lại là 1.8 vậy anh @ongtrieuhau 
-> Trường hợp này đơn vị muốn là 7.1 bệnh lĩnh thuốc Lao đã hướng dẫn thực hiện check bn lao và trạng thái chuyển tuyến = 5 rồi mà vẫn chưa lấy được mã đối tượng 7.1
![ảnh](https://github.com/user-attachments/assets/08736384-79f9-4c77-b08f-acb3fa07732f)

***

**Comment by vinh-dh** [comment]
> sao lại là 1.8 vậy anh @ongtrieuhau -> Trường hợp này đơn vị muốn là 7.1 bệnh lĩnh thuốc Lao đã hướng dẫn thực hiện check bn lao và trạng thái chuyển tuyến = 5 rồi mà vẫn chưa lấy được mã đối tượng 7.1

@le-an-87 anh đang rà soát lại quy trình của BN lao và trường hợp lãnh thuốc  theo đơn.

**Comment by vinh-dh** [comment]
1. Cập nhật [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
- Bổ sung giá trị cho cột `psdangky.trangthaichuyentuyen = 6`: Giấy hẹn lãnh thuốc.
- Bổ sung mô tả ràng buộc khi tiếp nhận bệnh tại module Register, đối với `psdangky.trangthaichuyentuyen = 5 hoặc 6 (Giấy hẹn lãnh thuốc)` .
- Bổ sung mô tả thông tin chuyển tuyến người bệnh lao khi tiếp nhận bệnh tại module Register, đối với `psdangky.trangthaichuyentuyen = 4 (Chuyển tuyến người bệnh khám và điều trị bệnh lao)` .
![image](https://github.com/user-attachments/assets/4993e072-3c37-42d1-a037-fa6dd4d9fca0)
![image](https://github.com/user-attachments/assets/83805d91-9f19-4659-a31d-2a21f2d3f6fd)

2. Cập nhật mô tả [ma_doituong_kcb](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/ma_doituong_kcb.md):
- Thay đổi thứ tự đối với `ma_doituong_kcb = '7.1'`. Từ `1.8 ⇒ 7.1 ⇒ 1.3` thành `1.10 ⇒ 7.1 ⇒ 1.1`.
- Thay đổi điều kiện ràng buộc đối với `ma_doituong_kcb = '7.1'`.
- Thay đổi thứ tự đối với `ma_doituong_kcb = '1.8'`. Từ `1.5 ⇒ 1.8 ⇒ 1.3` thành `7.1 ⇒ 1.8 ⇒ 1.1`.
- Thay đổi điều kiện ràng buộc đối với `ma_doituong_kcb = '1.8'`. 
![image](https://github.com/user-attachments/assets/452d83c6-aa8a-425d-a2ce-02c8a3f7317a)
![image](https://github.com/user-attachments/assets/39593065-4308-444c-8b54-fc031f4e5d7d)

**Comment by vinh-dh** [comment]
3. Cập nhật mô tả [ma_loai_kcb](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/ma_loai_kcb.md):
- Cập nhật điều kiện  đối với `ma_loai_kcb = '07'` (áp dụng đối với `bang1.ma_loai_kcb` và `checkin.ma_loai_kcb`).
![image](https://github.com/user-attachments/assets/256caf54-587e-47c5-89c4-ed5230b3cd02)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0912.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409121-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409121-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409121-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Thực hiện Mo-ta-he-thong/XML130/QD4570/ma_loai_kcb.md ![](https://i.imgur.com/tqOYdLS.png)

- ✨: **XML01.MA_LOAI_KCB** = 07 khi psdangky.trangthaichuyentuyen IN (5,6)

- ✨: Thực hiện Mo-ta-he-thong/XML130/QD4570/ma_doituong_kcb.md ![](https://i.imgur.com/1Rzz1jh.png)

- ✨: **XML01.MA_DOITUONG_KCB**

- ✨: ![](https://i.imgur.com/eVvUwns.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/127

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/130

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.
- Diễn giải lỗi: chưa lấy được mã 7.1

- Hình ảnh lỗi:
![ảnh](https://github.com/user-attachments/assets/deee6193-cb1b-4ce9-9b84-5e9cedb87684)
> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
coi lại chổ này anh @vinh-dh ơi.
-> bắt buộc nhập nơi giới thiệu thì có hướng giải quyết các bệnh củ anh ơi.
![ảnh](https://github.com/user-attachments/assets/356513aa-7517-45ab-8bdb-40235215a6d7)
***

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
bắt buộc nhập mã nơi giới thiệu thì hỗ trợ bảng kê 6556 thêm tùy cho chọn hiển thị Nơi chuyển đến luôn nhe anh.
![ảnh](https://github.com/user-attachments/assets/8230c169-c7ca-466a-9692-71a6e9ec3798)
***

**Comment by vinh-dh** [comment]
> coi lại chổ này anh @vinh-dh ơi.
> -> bắt buộc nhập nơi giới thiệu thì có hướng giải quyết các bệnh củ anh ơi.
> ![ảnh](https://github.com/user-attachments/assets/356513aa-7517-45ab-8bdb-40235215a6d7)

Ok, để anh cập nhật điều kiện bổ sung cho trường hợp này.

**Comment by ongtrieuhau-dh** [comment]
## <sub>📢 @le-an-87  </sub>

- ***Do chưa nhập Nơi giới thiệu***
- ![](https://i.imgur.com/SsQNKxx.png)

**Comment by le-an-87** [comment]
### **Trả lời vướng mắc**
alo anh @nghivanbi anh coi chốt hướng xử lý thế nào để biết hướng dẫn khác hàng thực hiện nhé anh.
chứ trước giờ bệnh nhân lao lãnh thuốc có nhập nơi giới thiệu đâu mà giờ nói do không nhập.
***

**Comment by vinh-dh** [comment]
> coi lại chổ này anh @vinh-dh ơi.
> -> bắt buộc nhập nơi giới thiệu thì có hướng giải quyết các bệnh củ anh ơi.
> ![ảnh](https://github.com/user-attachments/assets/356513aa-7517-45ab-8bdb-40235215a6d7)

1. Cập nhật [Mô tả XML130 - Bổ sung QĐ 4750](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750.md)
- Bổ sung điều kiện ràng buộc cột `psdangky.trangthaichuyentuyen` đối với người bệnh khám lao khi tiếp nhận bệnh.
![image](https://github.com/user-attachments/assets/c7fd94e8-0e73-4568-ab27-0ca37d7d02ae)

2. Cập nhật mô tả [ma_doituong_kcb](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/ma_doituong_kcb.md):
- Thay đổi điều kiện ràng buộc đối với `ma_doituong_kcb = '7.1'`. 
![image](https://github.com/user-attachments/assets/d108f7c8-8d1a-4517-8b59-fcf34e321223)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0914.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409140-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409140-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409140-NasDHSolutions.json)

## Nội dung thay đổi

- 🐛: **💼**: **_XML 4750 Bệnh nhân lao (BANT ngày) lấy sai mã đối tượng (BV Quảng ngãi)_**

- 🐛: Thực hiện: Mo-ta-he-thong/XML130/QD4570/ma_doituong_kcb.md ![](https://i.imgur.com/YyOLxCN.png)

- 🐛: **XML01.MA_DOITUONG_KCB** ![](https://i.imgur.com/MNeWvLS.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/127

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by le-an-87** [comment]
### **✔️KẾT QUẢ KIỂM TRA SẢN PHẨM**
***
> Hình ảnh chứng mình cho việc kiểm tra này.
![ảnh](https://github.com/user-attachments/assets/207dcb2e-738c-4f72-8cc3-32add1871a26)

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by le-an-87** [comment]
### **HoànThành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @le-an-87 , @nghivanbi
