### ISSUE TITLE
Yêu cầu hỗ trợ trường hợp 1 bệnh nhân có dữ liệu XML trong 2 tháng gây lệch số hồ sơ Admin

### ISSUE THREAD

**Issue by chauthanhtra** [dh-hos/THEO-DOI-THUC-HIEN#131]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.2: Phiếu ghi nhận Yêu cầu mới DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN YÊU CẦU CHỨC NĂNG MỚI</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Châu Thanh Trà**
-  ![ngay_mong_muon_hoan_thanh](https://img.shields.io/badge/Ngày%20mong%20muốn%20hoàn%20thành-:-blue?style=plastic&logo=github) **20/09/2024**
-  ![ngay_hoan_thanh](https://img.shields.io/badge/Ngày%20hoàn%20thành-:-blue?style=plastic&logo=github) **to_truong_ghi**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `92007`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **BVĐK QUẬN Ô MÔN**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `tra_omon_rep_bnnoitru_khonglenxml4750_17092024`
-  ![port_csdl](https://img.shields.io/badge/Port%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `5434`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](https://gofile.me/78TQg/isS3reyDm)
-  ![module](https://img.shields.io/badge/Phân%20hệ%20yêu%20cầu-:-blue?style=plastic&logo=github) `Admin`

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2018042470` - _**MaKB**_: `2407006676` - _**MaBA**_: `2024008587` _**NgayRV**_: `17/7/2024` - _**MaPhong**_: `GA1` - _**MaDV**_: `07` - _**ThangKT**_: `07` - _**NamKT**_: `2024`

###### ![chi_tiet_yeu_cau](https://img.shields.io/badge/Chi%20tiết%20yêu%20cầu%20-:-blue?style=for-the-badge&logo=github)

Bệnh nhân ra viện tháng 7 qua tháng 8 trả về điều trị rồi cho ra viện lại chỉnh về tháng 7 dữ liệu current.psxml có 2 dòng tháng 7 và tháng 8
- Admin lấy dữ liệu XML thì có bệnh nhân ở cả 2 tháng nên số hồ sơ bị sai so với Reports (Reports chỉ có XML tháng 7)
- Cần hỗ trợ chức năng fix lại XML trên Admin theo tháng quyết toán đúng của bệnh nhân

![](https://i.imgur.com/fgQo2mx.png)
![](https://i.imgur.com/XjrpDOy.png)
![](https://i.imgur.com/ypJqIfw.png)
![](https://i.imgur.com/gSCdaZK.png)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-09-23**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0918.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409181-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409181-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409181-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Yêu cầu hỗ trợ trường hợp 1 bệnh nhân có dữ liệu XML trong 2 tháng gây lệch số hồ sơ Admin_**

- ✨: ***Xử lý trùng ma_lk trong current.psxml*** _Thực hiện loại bỏ các hồ sơ bị trùng, **Đồng thời** cập nhật lại giá trị ma_lk, ngay_ttoan, thang_qt, nam_qt trường hợp trùng (các giá trị này được lấy chi tiết từ psdangky và bnnoitru dựa vào loaihosokcb)_

- ✨: Việc kiểm tra trùng này trong chức năng ***[Lấy dữ liệu]*** trên form ![](https://i.imgur.com/vXVq6SD.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/131

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Thời gian dự kiến hoàn thành kiểm tra: '25/9/2024'.
***
- Kiểm tra chức năng BLYC theo:
o Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
- Kiểm tra chức năng cơ bản của phân hệ trong qui trình khám chữa bệnh hoặc qui trình kho. Chứng minh bằng hình ảnh:
o Phiếu 01, 02, xuất XML.
o Nhập thuốc -> xuất thuốc -> tổng hợp.
o Có hình ảnh chứng mình cho việc kiểm tra này.
- File: copy sản phẩm đã kiểm thử thành công lên NAS: NAS\DuLieuCongTy\Modules -> Close Issue.
- Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.0918.2
***
>Lỗi, yêu cầu đã hoàn thành 

>- Nội dung: 

>  - 

>- Hình ảnh: 



***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi:

  - Xuất XML 4750 Bấm lấy dữ liệu thì phần mềm tạo thên 1 dòng bệnh nhân trong psxml 

- Hình ảnh lỗi:

![](https://i.imgur.com/KmRkHD0.png)
![](https://i.imgur.com/yFTg276.png)

> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0919.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409190-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409190-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32409190-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: **💼**: **_Yêu cầu hỗ trợ trường hợp 1 bệnh nhân có dữ liệu XML trong 2 tháng gây lệch số hồ sơ Admin_**

- ✨:***Chỉnh lỗi trùng hồ sơ khi lấy dữ liệu trên Form xuất 4750 (chức năng kiểm tra thiếu hồ sơ nội trú)*** ![](https://i.imgur.com/Aeg0Cku.gif)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN/issues/131

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau-informational?logo=github)](https://github.com/ongtrieuhau) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.0919.0
***
>Lỗi, yêu cầu đã hoàn thành 

>- Nội dung: 

>  - 

>- Hình ảnh: 



***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

- Diễn giải lỗi:

  - Admin mới trường hợp bệnh nhân XML ở 2 tháng bây giờ không xóa được
  - Bệnh nhân có 1 dòng tháng 7 Em thêm 1 dòng XML tháng 8 thì Admin không xóa được, 
  - Nếu có 2 dòng tháng 7 và 1 dòng tháng 8 thì phần mềm báo có 1 hồ sơ trùng rồi xóa 1 dòng tháng 7 và 1 dòng tháng 8 thì nó mới đúng

- Hình ảnh lỗi:

![](https://i.imgur.com/v8MoFhk.png)
![](https://i.imgur.com/bvrB9jY.png)

> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Chưa hoàn thành**
- Hoàn thành kiểm tra
- Phần mềm chưa đáp ứng đúng yêu cầu.
- Yêu cầu Tổ coder kiểm tra lại.

**Comment by chauthanhtra** [comment]
### **✔️KẾT QUẢ TEST**
***
Phần mềm HospitalAdmin.exe v.3.24.0919.1
***
>Lỗi, yêu cầu đã hoàn thành 

- Nội dung: 

  - Đã fix lỗi 1 hồ sơ có 2 tháng kế toán trên Admin , đã xóa được dữ liệu psxml trùng 2 dòng ở 2 tháng quyết toán khác nhau

- Hình ảnh: 

![](https://i.imgur.com/wvlTym8.png)
![](https://i.imgur.com/BgaoTz4.png)
![](https://i.imgur.com/IqB77fr.png)

***
> Trường hợp không đủ thông tin kiểm tra hoặc còn lỗi ghi nhận phản hồi cho CO.

>- Diễn giải lỗi:


>- Hình ảnh lỗi:



> Hình ảnh Phiếu 01, 02, xuất XML.

> Nhập thuốc -> xuất thuốc -> tổng hợp.

> Hình ảnh chứng mình cho việc kiểm tra này.

> Mô tả, hướng dẫn sử dụng chức năng cập nhật (nếu có).
***
##### 
>Phát sinh lỗi chức năng hiện tại -> Ghi nhận lỗi và ngưng test các vấn đề còn lại.

**Comment by chauthanhtra** [comment]
### **Hoàn Thành**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
***
- Tiến hành hỗ trợ khách hàng.
