### ISSUE TITLE
Hỗ trợ chức năng Import ICD 9 từ excel, hỗ trợ script áp mã ICD 9 cho danh mục cận lâm sàng theo mã tương đương (Theo biên bản họp)

### ISSUE THREAD

**Issue by ongtrieuhau-dh** [dh-hos/THEO-DOI-THUC-HIEN#16]
![image](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/155862740/7f20bc84-9c8e-42d2-b2b2-466a4d44e8dc)

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0628.9 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32406289-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32406289-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32406289-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Hỗ trợ chức năng Import ICD 9 từ excel  COD thực hiện.

- ✨: Hỗ trợ script áp mã ICD 9 cho danh mục cận lâm sàng theo mã tương đương 

COD thực hiện.

![](https://i.imgur.com/3dMDbUf.png)

![](https://i.imgur.com/pnX7oj1.png)

![](https://i.imgur.com/yJQnkFQ.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/16

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by nghivanbi** [comment]
TK, HT test chức năng này nhé

**Comment by le-an-87** [comment]
Đã hỗ trợ nhập = file excel và cập nhật vào danh mục cls
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/ba68f598-b8c7-49f5-963f-137e1574cd98)
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/8f719db4-5ef8-4807-a42f-af13a9d8de14)
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/ac72db14-1e8e-44c6-8a76-fdb9d99e0abd)
![ảnh](https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/assets/96155021/4ba87bfd-5afb-444f-9220-9013747aa010)
