### ISSUE TITLE
LỖI XML1: MA_DOITUONG_KCB

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN#67]

**Comment by minhduc2it** [comment]
Data: duc_donghai_lydovv
MABN: 2018000214 - MAKB: 2407000018 - NgayKCB: 15/7/2024
Dữ liệu psdangky ghi nhận:
tuyen = 0
tuyenbv = 2
mabvdk = 96001
mabvkb = 95007
tuyenxml = 0
trangthaichuyentuyen = 0

Hiện tại dữ liệu XML1: MA_DOITUONG_KCB = 9 đang lấy chưa đúng với [Mô tả Table xml130.bang01 - [Phụ lục - Mô tả XML130 - Bổ sung QĐ 4750].md
](https://github.com/dh-hos/Mo-ta-he-thong/blob/main/XML130/QD4570/Table%20xml130.bang01%20-%20%5BPh%E1%BB%A5%20l%E1%BB%A5c%20-%20M%C3%B4%20t%E1%BA%A3%20XML130%20-%20B%E1%BB%95%20sung%20Q%C4%90%204750%5D.md#user-content-fnref-2024-07-12-01-a8ba7ed4d8453f16e568f2119a0a489d)
![image](https://github.com/user-attachments/assets/1c332191-cafa-409e-93e1-61ad7f76951c)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-17**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
@minhduc2it lấy Register mới nhất nhập lại trường hợp này xem có bị tình trạng này hông nhé, theo đúng thì cột tuyenxml phải bằng 1.

**Comment by vinh-dh** [comment]
Bệnh nhân này ngoài tỉnh mà `tuyenxml = 0`, vậy hoặc là Reg đang sử dụng bản cũ hoặc là Reg bị sai rồi đó @minhduc2it.

**Comment by vinh-dh** [comment]
Nếu đúng mô tả của `ma_doituong_kcb` thì khi người bệnh ngoài tỉnh (`tuyenxml = 1`) thì trường hợp này `ma_doituong_kcb = 3.3`

**Comment by minhduc2it** [comment]
Đã kiểm tra Do BV Chọn sai Có Giấy chuyển khi đăng ký khám (Bv Tuyến huyện không có giấy chuyển)

**Comment by ongtrieuhau-dh** [comment]
### ✅ TỔ LẬP TRÌNH - HOÀN THÀNH ✅
-  📣 **Nhờ kiểm tra sản phẩm**: @minhduc2it , @le-an-87  @nghivanbi

**Comment by nghivanbi** [comment]
### 💡KIỂM TRA SẢN PHẨM💡
---------------------------------------------------------------------
📣 **Phân công kiểm tra**: @le-an-87, @minhduc2it 
📣 **Hạn hoàn thành mong muốn**:

**Comment by le-an-87** [comment]
- ✔️ Đã tiếp nhận
- ⌛ Phân công: @minhduc2it 
***
- Liên hệ khách hàng hỗ trợ nội dung yêu cầu:
 1. Ghi nhận yêu cầu.
 2. Ghi nhận kết quả hỗ trợ.

**Comment by minhduc2it** [comment]
**HOÀN THÀNH**
✔️Hoàn thành kiểm tra
✔️Kết quả kiểm tra đạt yêu cầu
---
> Đã kiểm tra Do BV Chọn sai Có Giấy chuyển khi đăng ký khám (Bv Tuyến huyện không có giấy chuyển)

Đã hướng dẫn BV
