### ISSUE TITLE
XML3 chưa lấy Nguoi_thuc_hien cho Mã Nhóm 2

### ISSUE THREAD

**Issue by minhduc2it** [dh-hos/THEO-DOI-THUC-HIEN#83]

**Comment by minhduc2it** [comment]
Data: duc_omon_nguoithuchiendiag
Link dữ liệu: https://gofile.me/78TQg/luDNtovir

MABN: 2019050723  - MAKB: 2407002124 - NGAYKB: 02/07/2024
MA CLS: CH493
CLS XQuang chưa lấy Nguoi_thuc_hien trên XML3
Dữ liệu ghi nhận pskhamha.manv =96


![image](https://github.com/user-attachments/assets/2d2f5ced-4564-410f-9408-e1bead70e3eb)

![image](https://github.com/user-attachments/assets/b9a300b7-34d4-4b51-80f9-de22b72f7efe)

![image](https://github.com/user-attachments/assets/c625ea90-ad39-4094-b5e2-ce7fb109cccc)

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ✔️ **Đã tiếp nhận** 
- ⌛ Thời gian hoàn thành dự kiến: **2024-07-26**


[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.]

**Comment by ongtrieuhau-dh** [comment]
- [ ] Thực hiện công việc

**Comment by ongtrieuhau-dh** [comment]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task

**Comment by ongtrieuhau-dh** [comment]
## HD.05 [^HD05]
-  ❌ **Từ chối tiếp nhận** 
- 📣 **Nguyên nhân**: _Không tìm thấy dữ liệu trên máy chủ_


![Image](https://github.com/user-attachments/assets/dcb4f5bc-7be3-4837-b78a-681232544596)



[^HD05]: Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
đủ thông tin

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0724.0 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407240-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407240-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407240-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Yêu cầu - Bổ sung bảng XML 11 (GIẤY CHỨNG NHẬN NGHỈ HƯỞNG BHXH) ![](https://i.imgur.com/1pHSAuu.png)

- ✨: Yêu cầu - Mô tả và thực hiện hỗ trợ gởi bệnh nhân BANT thanh toán ngày XML1.ma_loai_kcb ![](https://i.imgur.com/HMSzYM7.png)

- 🐛: Fix lỗi: XML3 chưa lấy Nguoi_thuc_hien cho Mã Nhóm 2 ![](https://i.imgur.com/IeSaP0d.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/83

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

- ☑: https://github.com/dh-hos/Yeu_cau_ho_tro/issues/199

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by gh-dh-bot-01** [comment]
### 📣📣📣 HospitalAdmin.exe v.3.24.0724.1 [⬇️OneDrive](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407241-OneDrive.json) [⬇️GoogleStorage](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407241-GoogleStorage.json) [⬇️NasDHSolutions](https://dh-hos-code.github.io/directTo/?&redirect_url=https%3A%2F%2Fo-dh-007-default-rtdb.asia-southeast1.firebasedatabase.app%2F%2FdirectTo%2FHospitalAdminexe%2F32407241-NasDHSolutions.json)

## Nội dung thay đổi

- ✨: Yêu cầu - Bổ sung bảng XML 11 (GIẤY CHỨNG NHẬN NGHỈ HƯỞNG BHXH) ![](https://i.imgur.com/1pHSAuu.png)

- ✨: Yêu cầu - Mô tả và thực hiện hỗ trợ gởi bệnh nhân BANT thanh toán ngày XML1.ma_loai_kcb ![](https://i.imgur.com/HMSzYM7.png)

- 🐛: Fix lỗi: XML3 chưa lấy Nguoi_thuc_hien cho Mã Nhóm 2 ![](https://i.imgur.com/IeSaP0d.png)

- ☑: https://github.com/dh-hos/THEO-DOI-THUC-HIEN-4750/issues/83

- ☑: https://github.com/dh-hos/To_Ho_Tro/issues/20

- ☑: https://github.com/dh-hos/To_Trien_Khai/issues/57

- ☑: https://github.com/dh-hos/Yeu_cau_ho_tro/issues/199

- ☑: https://github.com/dh-hos/To_Lap_Trinh/issues/519

<div align="right">

 [![](https://img.shields.io/badge/-Th%E1%BB%B1c%20hi%E1%BB%87n%20b%E1%BB%9Fi%3A%20%40ongtrieuhau--dh-informational?logo=github)](https://github.com/ongtrieuhau-dh) [![](https://img.shields.io/badge/-Xem%20l%E1%BB%8Bch%20s%E1%BB%AD%20phi%C3%AAn%20b%E1%BA%A3n-informational?logo=github)](https://github.com/dh-hos-code/HospitalAdmin.exe?tab=readme-ov-file#readme) [![](https://img.shields.io/badge/Nh%E1%BA%ADn%20th%C3%B4ng%20b%C3%A1o%20tr%C3%AAn%20Telegram-2CA5E0?style=flat-squeare&logo=telegram&logoColor=white)](https://t.me/dhhoscodemsifiles)
</div>

**Comment by minhduc2it** [comment]
> ## HD.05 [1](#user-content-fn-HD05-d18ef4921d0e8ca14c3486bbf0e0b866)
> * ❌ **Từ chối tiếp nhận**
> * 📣 **Nguyên nhân**: _Không tìm thấy dữ liệu trên máy chủ_
> 
> ![Image](https://private-user-images.githubusercontent.com/155862740/351563684-dcb4f5bc-7be3-4837-b78a-681232544596.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDUxOTAsIm5iZiI6MTcyMTgwNDg5MCwicGF0aCI6Ii8xNTU4NjI3NDAvMzUxNTYzNjg0LWRjYjRmNWJjLTdiZTMtNDgzNy1iNzhhLTY4MTIzMjU0NDU5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwNzA4MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWZiZmMwNjU0Y2M3NjkzNTYyMjFlMTA3MzFhMjVhMzA0MTBlZDEyZDQ5MWEyYTkzNWEyMGY5ZDhiYThjNGI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M_QqxnXkon7q7419PxHSRLNLi02p52yaNPuORUCXXVQ)
> 
> ## Footnotes
> 1. Thời gian phải tiếp nhận ( Bình thường: 120 phút. Gấp: 60 phút) [Đối với các BL “Gấp” thời gian xử lý 4h, trường hợp không kịp bắc buộc phải đề ra các khắc phục tạm thời (Sql, lùi bản cũ…); Mức độ ưu tiên các lỗi “Gấp”: GĐ, tổ trưởng CO, tổ trưởng HT, tổ trưởng TK, nhân viên HT, nhân viên TK.] Nghĩa vụ: ghi nhận vi phạm nếu có tại HD.04, phản hồi
>    đủ thông tin [↩](#user-content-fnref-HD05-d18ef4921d0e8ca14c3486bbf0e0b866)

Vào Port 5434 nha anh @ongtrieuhau-dh

**Comment by minhduc2it** [comment]
Đã kiểm tra CLS XQuang đã lấy Nguoi_thuc_hien trên XML3

![image](https://github.com/user-attachments/assets/96b2c17a-6786-485d-8a21-9b877fb523cd)
